# Assignment 3

## Task 1

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [301]:
def divide(n,n1):
    try:
        return n/n1
    except Exception as e:
        print(e)
        return n


In [302]:
divide_by_Zero(5,0)

division by zero


5

2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [308]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

x=[f"{x} {y} {z}" for x in subjects for y in verbs for z in objects  ]
for i in x:
    print(i)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2

1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [253]:
#reference np.vander
def myvander(x,n=None,increasing=False):
    import numpy as np
    n= len(x) if n==None else n
    a=np.empty([len(x),n])
    for columns in range(n):
        for rows,i in enumerate(x):
            a[rows][columns]=pow(i,columns)
            
    np.set_printoptions(suppress=True) 
    if increasing==True:
        return a
    else:
        for x,i in enumerate(a):
            a[x]=i[::-1]
        return a

In [269]:
# When n is provided and increasing is True
x = np.array([2,3,4,1])
n = 6
myvander(x,n,increasing=True)

array([[   1.,    2.,    4.,    8.,   16.,   32.],
       [   1.,    3.,    9.,   27.,   81.,  243.],
       [   1.,    4.,   16.,   64.,  256., 1024.],
       [   1.,    1.,    1.,    1.,    1.,    1.]])

In [309]:
# When n is not provided and increasing is True
x = np.array([2,3,4,1])
n = 6
myvander(x,increasing=True)

array([[ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.],
       [ 1.,  4., 16., 64.],
       [ 1.,  1.,  1.,  1.]])

In [310]:
# When n is provided and increasing is False
x = np.array([2,3,4,1])
n = 6
myvander(x,n,increasing=False)

array([[  32.,   16.,    8.,    4.,    2.,    1.],
       [ 243.,   81.,   27.,    9.,    3.,    1.],
       [1024.,  256.,   64.,   16.,    4.,    1.],
       [   1.,    1.,    1.,    1.,    1.,    1.]])

In [311]:
# When n is not provided and increasing is False
x = np.array([2,3,4,1])
n = 6
myvander(x,increasing=False)

array([[ 8.,  4.,  2.,  1.],
       [27.,  9.,  3.,  1.],
       [64., 16.,  4.,  1.],
       [ 1.,  1.,  1.,  1.]])